import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import { Star } from "./component/StarBackground";
import { PageMotion } from "./component/motion/global/pageMotion";
import { SetInitialTheme } from "./component/SetInitialTheme";
import Footer from "./component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Masum's Portfolio",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <SetInitialTheme />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
          <Star />
        <PageMotion>
        {children}
        </PageMotion>
        <Footer />
      </body>
    </html>
  );
}
